/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:69cee590-6ade-4c45-a2fb-b26f9b661554",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_yhftlq5Bz",
    "aws_user_pools_web_client_id": "592v8oiq0s1n7j8e1j648i3kgc",
    "oauth": {
        "domain": "abcwuaui52f90959-52f90959-prod.auth.us-west-2.amazoncognito.com",
        "scope": [
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://account.abcwua.org/",
        "redirectSignOut": "https://www.abcwua.org/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS"
};


export default awsmobile;
