/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:69cee590-6ade-4c45-a2fb-b26f9b661554",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_yhftlq5Bz",
    "aws_user_pools_web_client_id": "592v8oiq0s1n7j8e1j648i3kgc",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "authenticationFlowType": "USER_PASSWORD_AUTH"
};


export default awsmobile;
